name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
        
    - name: Build backend
      run: |
        cd backend/bookproject
        chmod +x gradlew
        ./gradlew build --no-daemon
        
    - name: Build frontend
      run: |
        cd frontend
        yarn install --frozen-lockfile
        yarn build
        
    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp -r backend/bookproject/build/libs/*.jar deploy/
        cp -r frontend/build deploy/frontend-build
        
    # 여기에 실제 배포 단계를 추가할 수 있습니다
    # 예: AWS S3, Heroku, Docker Hub 등
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: deploy/
        retention-days: 7 